### PR TITLE
Rename points_varaible_size.py to points_variable_size.py

### PR DESCRIPTION
**Pull request by gregorni**
### Description

"variable" was misspelled

### List of changes

- renamed the file

### CODE REVIEW

**Comment by einarf** [comment]
Thanks!

**Comment by gregorni** [comment]
Erm, you closed the PR without merging. Was this accidental? The file wasn't renamed.

**Comment by einarf** [comment]
Ops. Yeah was on phone and just realized now. Sorry!

**Comment by einarf** [comment]
> You can also just rename the file yourself.

It's a mircale every time someone makes a PR fixing even the smallest thing, so not merging would be bad and also not respecing other people's time.

Thanks again for the fix 👍

**Pull request merged**
