### PR TITLE
Introspect storage blocks #540

### PR DESCRIPTION
**Pull request by einarf**
Quick and dirty introspection of storage blocks. It works, but needs to look through it.

I do wonder if we should move program introspection to a function in the context so we can reuse code between program and compute shader. Just need to check version code and skip the ssbo part?

### CODE REVIEW

**Comment by szabolcsdombi** [comment]
the reason this was not implemented is that storage blocks are only available in gl versions where explicit binding is also available.
it is good to have this implemented as well.

**Comment by szabolcsdombi** [comment]
maybe we also need to update the .pyi file.

**Comment by einarf** [comment]
> maybe we also need to update the .pyi file.

Definitely. I still need to look through this at least one more time. It was a quick start.

**Comment by einarf** [comment]
That should be all. Need to clean up some docstrings etc, but that can be done separately.

**Pull request merged**
