### PR TITLE
fix for issue #390

### PR DESCRIPTION
**Pull request by Leterax**
Check OpenGL version before creating a Compute-Shader.

### Description

Version is now checked before creating a Compute-Shader

### List of changes

- **added** Version check
- **removed** ...
- **fixed** ...
- **changed** ...

### CODE REVIEW

**Comment by Leterax** [comment]
The error message is probably too vague, but I want sure how to word it correctly.

**Comment by einarf** [comment]
Not 100% if this is the right way to do it. We might need to actually check if the compute shader extension is available. Need to look into this,

**Comment by Leterax** [comment]
It seems you can get away with using ARB_compute_shader <https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_compute_shader.txt>, but this requires OpenGL 4.2. 
So we can be sure they arent supported below 4.2 but need to check for ARB_compute_shader if the version is below 4.3.

**Comment by Leterax** [comment]
after some googling I found this:
http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-12-opengl-extensions/
they suggest this to find if an extension is supported:
```c
int NumberOfExtensions;
glGetIntegerv(GL_NUM_EXTENSIONS, &NumberOfExtensions);
for(i=0; i<NumberOfExtensions; i++) {
  const GLubyte *ccc=glGetStringi(GL_EXTENSIONS, i);
  if ( strcmp(ccc, (const GLubyte *)"GL_ARB_compute_shader") == 0 ){
    // The extension is supported by our hardware and driver
  }
}
```

**Comment by einarf** [comment]
Yup. Just need to make sure the context loads a `set` of extension strings that could be checked.

**Comment by Leterax** [comment]
would that then be saved in the actual MGLContext struct?

**Comment by einarf** [comment]
Yup. Just need to add it so extensions can be queried on the C++ and python side, It's available in C++ only. Not very practical. Doing a `extension in extensions` check on a `set` in python should be fast enough.

**Comment by Leterax** [comment]
yeah. set contains checks are plenty fast enough. I have no idea what I'm doing, but I would imagine something like this would work:
```cpp
PyObject* extensions = PySet_New(NULL);
int NumberOfExtensions;
glGetIntegerv(GL_NUM_EXTENSIONS, &NumberOfExtensions);
for(i=0; i<NumberOfExtensions; i++) {
  const GLubyte *ccc=glGetStringi(GL_EXTENSIONS, i);
  PySet_Add(extensions, PyUnicode_FromString(ccc));
}
```
I'm not entirely sure if you can just directly convert GLubyte* to a unicode string, because a null byte terminated char buffer is expected.

**Comment by Leterax** [comment]
PySet_New can also take an iterable, so it might be possible without the for loop adding to the set.

**Comment by einarf** [comment]
`Context` just needs a pre-loaded set of extenstions that are created during context creation or something.

**Comment by einarf** [comment]
Need to do some tests before deciding on this one. It might actually be correct using version in the context because this indicates the application wanted to add this limitation.

**Comment by einarf** [comment]
After looking more into this: Compute shaders are supported if either the version code is high enough OR there is a known compute shader extension available. This PR only covers the first part. I'm not entirely sure what all the valid compute shader extension strings are.

What we can do it add some flags in the `Context` itself.

**Comment by einarf** [comment]
We'll add a check after the refactoring. It shouldn't be too hard. Closing this PR and commenting in the original issue.

**Pull request closed without merging**
