### PR TITLE
Allow depth only framebuffer

### PR DESCRIPTION
**Pull request by einarf**

### CODE REVIEW

**Comment by yoyonel** [comment]
Yeaaaahhhhhhhhhh ^^
Can i be in collab list now ? :p

**Comment by einarf** [comment]
There 😄 
https://github.com/moderngl/moderngl/commit/41669be870485aee335e85396b7f11935bd8a3b3

You've had the contributors role on discord for a while also.

**Comment by yoyonel** [comment]
Hé hé nice, good motivation to perform more !
Next step, pull request with a "true" shadow (mapping) sample ! 
Not very difficult (with this merge) and pretty good visual result (for gallery/demonstration). 
Stay tune !

**Comment by einarf** [comment]
I made one in moderngl-window as least :https://github.com/moderngl/moderngl-window/blob/master/examples/advanced/shadow_mapping_56.py

Not very fancy. Just directional shadows from the opengl tutorial.

The reason for the recent activity is that I'm trying to revive moderngl 5. All new features was going into 6, but the progress on getting that released is slow... to for the sake of progress we'll try to do a 5.6, 5.7 and maybe a 5.8 this year.

**Comment by yoyonel** [comment]
> I made one in moderngl-window as least :https://github.com/moderngl/moderngl-window/blob/master/examples/advanced/shadow_mapping_56.py
> 
> Not very fancy. Just directional shadows from the opengl tutorial.
> 
> The reason for the recent activity is that I'm trying to revive moderngl 5. All new features was going into 6, but the progress on getting that released is slow... to for the sake of progress we'll try to do a 5.6, 5.7 and maybe a 5.8 this year.

Oki interresting ... i can add a shadow sample like yours with PCF filtering (https://graphics.pixar.com/library/ShadowMaps/paper.pdf) and one with Poisson filtering (http://www.cs.cmu.edu/afs/cs/academic/class/15462-s15/www/lec_slides/p51-cook.pdf ) => (very) simple 😏/old school. 
Both are very simples and close to the OpenGL driver/moderngl core rendering.
Can it be interesting ?

**Comment by einarf** [comment]
That would be awsome. I'll be handleing PRs on the fly. Examples are always welcome. For features that should ideally be discussed first at least. (Discord or in issue)

**Pull request merged**
