### PR TITLE
Remove redundant code from example

### PR DESCRIPTION
**Pull request by kmaork**
Removed two functions that are the same as the functions they override

### CODE REVIEW

**Comment by einarf** [comment]
Thanks!

**Comment by einarf** [comment]
Why remove the initializer?

**Comment by kmaork** [comment]
Hey, I removed it because it's redundant - it only calls super with the same arguments. Removing it will have no effect except for clearing up the code a little bit :)

**Comment by einarf** [comment]
Yup. Derp. Let's just merge this.

**Pull request merged**
