### PR TITLE
Complete addition of DEPTH_CLAMP along with its documentation

### PR DESCRIPTION
**Pull request by compik710**
### Description

Recently faced with the problem of depth clipping when using projection matrices. DEPTH_CLAMP easily solves this problem, so it was not bad to add it here.

### List of changes

- **added** DEPTH_CLAMP and its documentation

### CODE REVIEW

**Comment by szabolcsdombi** [comment]
This is not a backward compatible change. I think existing user already use the enable_direct for this use case. If we add the depth clamp flag to the enable only, existing unchanged project get a lot of `glDisable(DEPTH_CLAMP)` calls on every `enable_only()` and every scope enter/exit. Probably eliminating the effect of their existing enable_direct calls.

I think it would be possible to add a `ctx.depth_clamp` value.
By default it is None meaning there is no depth clamp range.
When it is set to a (float, float) pair it will call `glEnable(GL_DEPTH_CLAMP)` and `glDepthRange()`.

It is possible we also want a scope variant of this `depth_clamp`.
Maybe it should be called `depth_clamp_range`.

This must be discussed first.
@einarf what do you think?

**Comment by einarf** [comment]
> I think it would be possible to add a `ctx.depth_clamp` value.
> By default it is None meaning there is no depth clamp range.
> When it is set to a (float, float) pair it will call `glEnable(GL_DEPTH_CLAMP)` and `glDepthRange()`.

More fan of this solution 👍

**Comment by compik710** [comment]
The point is that DEPTH_CLAMP takes into account clipping not only for glDepthRange, but also for the perspective matrix used in the vertex shader. So it would be better to make a separate DEPTH_CLAMP control.

**Comment by szabolcsdombi** [comment]
Some related documentations:
[gl core spec 4.5](https://registry.khronos.org/OpenGL/specs/gl/glspec45.core.pdf) page 434
[gl core spec 3.3](https://registry.khronos.org/OpenGL/specs/gl/glspec33.core.pdf) page 100
[glDepthRange](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDepthRange.xhtml)
[glEnable](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glEnable.xhtml)

The spec states the values for clipping are used from the depth range setter function.
So the `ctx.depth_clamp_range: Tuple[float, float] | None` is the proper way to do it in moderngl.

Also it would be a good opportunity to look into `glClipControl(GL_UPPER_LEFT, GL_ZERO_TO_ONE);`
This function call is not always available. It changes the OpenGL coordinate system to be the same as in Vulkan.
I think this should also be added as a boolean property `ctx.clip_control_vulkan` or similar.

**Comment by compik710** [comment]
@szabolcsdombi Looks like I got your idea.

It turns out you need to move DEPTH_CLAMP from `ctx.enable()` to `ctx.depth_clamp`? This will take a little more time, but this way of calling will look quite elegant and solve the backward compatibility problem.
I'll try to do this.

**Comment by compik710** [comment]
The main PR task has been completed.

**Comment by szabolcsdombi** [comment]
depth clamp is just the flag to enable/disable the depth range set by glDepthRange
This can be represented with a single property on the python side `depth_clamp_range`
internally in C there are 3 values, `bool depth_clamp` you already implemented this, and `float depth_range[2]`
I do not consider setting the `depth_clamp` boolean flag from python pythonic enough. You should not think in flags.
The way you can control the flag is by setting the range to a float pair or None.
when setting the range to None, it is equivalent of disabling the range as one would expect.
setting the range to a float pair sets the clamp to enable.
This way the user does not have to maintain two values serving the same purpose.

I review this a bit later when I have more time available. I am sure we will have this feature very soon.

**Comment by compik710** [comment]
I checked `glDepthRange` through PyOpenGL, it simply normalizes the depth for example from [0, 1] to [0.8, 1] and the image does not change. There is no mention of `DEPTH_CLAMP` in the documentation for `glDepthRange`.

https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDepthRange.xhtml

**Comment by compik710** [comment]
If I understand you correctly:
By default `ctx.depth_clamp_range = None`
And if there is a call from the user:
- `ctx.depth_clamp_range = None` It will `glEnable(GL_DEPTH_CLAMP)` and `glDepthRange(0, 1)`
- `ctx.depth_clamp_range = (near, far)` It will `glDisable(GL_DEPTH_CLAMP)` and `glDepthRange(near, far)`

I'm worried about the functionality being cut.
Do you think `glDepthRange(near, far)` is not needed with enabled `GL_DEPTH_CLAMP`?

**Comment by compik710** [comment]
@szabolcsdombi PR is ready.
Replaced `ctx.depth_clamp` with `ctx.depth_clamp_range`.
And also added a few lines to the documentation.

The solution is interesting, but it worked for me.

**Comment by compik710** [comment]
So, do you need anything else for PR?
Everything seems to be ready. For `ctx.clip_control_vulkan` you need another PR.

Although in this case it is worth thinking about ModernVulkan~

**Comment by szabolcsdombi** [comment]
I take a look now,

`ctx.clip_control_vulkan` will be another PR, I probably make it myself.
It can be used for vulkan interoperability or when someone wants to prepare porting the app to vulkan. We already have spv support, we lack this flag.

**Pull request merged**
