### PR TITLE
Added example to vertex_array.py

### PR DESCRIPTION
**Pull request by mrdaybird**
### Description
*(Note: First-Time contributor here. Constructive Feedback appreciated. )*

Added an example to index_buffer in vertex_array.py. My motivation for this was there were no examples anywhere on moderngl docs and this functionality was mysterious to me as someone new to OpenGL. This will definitely help first-time learners of OpenGL(not specifically moderngl).  
 
### List of changes

- **added** a simple example of rendering a square using index_buffer

### CODE REVIEW

**Comment by einarf** [comment]
Thanks. This only shows the simple vertex array creation. Should probably have both.

**Comment by mrdaybird** [comment]
Are you referring to rendering with different modes? If not, any links or sites?
BTW, I just started learning OpenGL and as a python developer, moderngl was my first choice. So, I was thinking of improving the moderngl documentation while learning OpenGL because it is hard to find good guides or book that teach OpenGL in python.

**Comment by einarf** [comment]
> Are you referring to rendering with different modes? If not, any links to refer to? BTW, I just started learning OpenGL and as a python developer, moderngl was my first choice. So, I was thinking of improving the moderngl documentation while learning OpenGL because it is hard to find good guides or book that teach OpenGL in python.

This is a great idea. I can merge this later and do some tweaks to make it simpler for now.

**Comment by mrdaybird** [comment]
Thanks for your reply. I think you can merge with changes for now. But can give some references or examples about what changes you are talking about? Excited for contributing to ModernGL. (I will ask for any in advice or reviews in the Discord. Thank you beforehand.)

**Comment by einarf** [comment]
Looking into this more: The location of this docstring is a bit misplaced I think. Will keep this hanging around until docs are properly resolved.

**Comment by einarf** [comment]
Closing this. I have things ready in a branch, Thanks for the PR!

**Pull request closed without merging**
